// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4o9-dHNqnNzTdXl6I9YUb2avRMCi4jaI',
    appId: '1:526258473410:web:f6d98bfb4cdd2f4ddaee5b',
    messagingSenderId: '526258473410',
    projectId: 'recipeproject-7b80e',
    authDomain: 'recipeproject-7b80e.firebaseapp.com',
    storageBucket: 'recipeproject-7b80e.appspot.com',
    measurementId: 'G-NHRR8P46ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJK4k2Ew0-BETrpDlFASu6BqSeyoJZ_3U',
    appId: '1:526258473410:android:96bb825c8598f716daee5b',
    messagingSenderId: '526258473410',
    projectId: 'recipeproject-7b80e',
    storageBucket: 'recipeproject-7b80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5yLhy99FmbzgcaTBj0ZUaRsaFOJ5PDI',
    appId: '1:526258473410:ios:efa971b1c02ed4c6daee5b',
    messagingSenderId: '526258473410',
    projectId: 'recipeproject-7b80e',
    storageBucket: 'recipeproject-7b80e.appspot.com',
    iosBundleId: 'com.example.recipeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5yLhy99FmbzgcaTBj0ZUaRsaFOJ5PDI',
    appId: '1:526258473410:ios:efa971b1c02ed4c6daee5b',
    messagingSenderId: '526258473410',
    projectId: 'recipeproject-7b80e',
    storageBucket: 'recipeproject-7b80e.appspot.com',
    iosBundleId: 'com.example.recipeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4o9-dHNqnNzTdXl6I9YUb2avRMCi4jaI',
    appId: '1:526258473410:web:8cb28e2383f879e2daee5b',
    messagingSenderId: '526258473410',
    projectId: 'recipeproject-7b80e',
    authDomain: 'recipeproject-7b80e.firebaseapp.com',
    storageBucket: 'recipeproject-7b80e.appspot.com',
    measurementId: 'G-DG5X0RXZ2H',
  );
}
